version: '3'
services:
  app:
    image: langchain-streamlit-agent:latest
    build:
      context: .
    volumes:
      - ./streamlit_agent/:/usr/app/streamlit_agent:cached
      - ./poetry.lock:/usr/app/poetry.lock:cached
      - ./pyproject.toml:/usr/app/pyproject.toml:cached
    ports:
      - 8080:8051
